### ISSUE TITLE
Initial map zoomout

### ISSUE THREAD

**Issue by codermanu** [codermanu/3D-Metaphorical-Data-Visualization-for-Pandemics#8]

**Comment by Lahirutech** [comment]
![image](https://user-images.githubusercontent.com/19344653/100619004-8eb4be00-3342-11eb-8d8f-a7be032f66cc.png)

**Comment by Lahirutech** [comment]
- [x] Create Globe with interactivity 

- [ ] Render and Visualize dataset to the Globe

- [ ] Combine the mushroom metaphor on top of the globe
